/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package house_cleaning_booking_system;

import javax.swing.JOptionPane;

/**
 *
 * @author ITLAB1-PC19-STUDENT
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Login = new javax.swing.JPanel();
        loginpanel = new javax.swing.JPanel();
        logintxt_username = new javax.swing.JLabel();
        login_username = new javax.swing.JTextField();
        logintxt_password = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        LoginButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ForgotPasswordButton = new javax.swing.JButton();
        login_password = new javax.swing.JPasswordField();
        CreateAccount = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ca_txtfullname = new javax.swing.JLabel();
        ca_txtusername = new javax.swing.JLabel();
        ca_txtpassword = new javax.swing.JLabel();
        ca_fullname = new javax.swing.JTextField();
        ca_username = new javax.swing.JTextField();
        ca_password = new javax.swing.JPasswordField();
        ca_createbutton = new javax.swing.JButton();
        ca_backbutton = new javax.swing.JButton();
        ca_txtemail = new javax.swing.JLabel();
        ca_email = new javax.swing.JTextField();
        ca_txtemail1 = new javax.swing.JLabel();
        ca_phonenumber = new javax.swing.JTextField();
        ca_txtemail2 = new javax.swing.JLabel();
        ca_birthdate = new javax.swing.JTextField();
        ca_txtaddress = new javax.swing.JLabel();
        ca_txtemail3 = new javax.swing.JLabel();
        ca_age = new javax.swing.JTextField();
        ca_address = new javax.swing.JTextField();
        ResetConfirm = new javax.swing.JPanel();
        ResetPassword = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rp_txtname = new javax.swing.JLabel();
        rp_name = new javax.swing.JTextField();
        rp_findbutton = new javax.swing.JButton();
        rp_backbutton = new javax.swing.JButton();
        sidePanel = new javax.swing.JPanel();
        CraeteAccountButton = new javax.swing.JButton();
        ResetPasswordBUtton = new javax.swing.JButton();
        AboutButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOUSE CLEANING BOOKING SYSYTEM");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "WELCOME TO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 120));

        Login.setBackground(new java.awt.Color(204, 204, 255));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginpanel.setBackground(new java.awt.Color(204, 204, 255));
        loginpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        loginpanel.setOpaque(false);
        loginpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logintxt_username.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logintxt_username.setForeground(new java.awt.Color(255, 255, 255));
        logintxt_username.setText("USERNAME:");
        loginpanel.add(logintxt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        login_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginpanel.add(login_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 320, 30));

        logintxt_password.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logintxt_password.setForeground(new java.awt.Color(255, 255, 255));
        logintxt_password.setText("PASSWORD:");
        loginpanel.add(logintxt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        CreateButton.setBackground(new java.awt.Color(255, 255, 255));
        CreateButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        CreateButton.setForeground(new java.awt.Color(51, 51, 51));
        CreateButton.setText("CREATE ACCOUNT");
        CreateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });
        loginpanel.add(CreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        LoginButton1.setBackground(new java.awt.Color(255, 255, 255));
        LoginButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        LoginButton1.setForeground(new java.awt.Color(51, 51, 51));
        LoginButton1.setText("LOGIN");
        LoginButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButton1ActionPerformed(evt);
            }
        });
        loginpanel.add(LoginButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 132, -1));

        jLabel2.setText("or");
        loginpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 19, -1));

        ForgotPasswordButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ForgotPasswordButton.setForeground(new java.awt.Color(51, 51, 255));
        ForgotPasswordButton.setText("forgot password");
        ForgotPasswordButton.setBorder(null);
        loginpanel.add(ForgotPasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        login_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginpanel.add(login_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 320, 30));

        Login.add(loginpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 420, 320));

        jTabbedPane1.addTab("tab1", Login);

        CreateAccount.setBackground(new java.awt.Color(204, 204, 255));
        CreateAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ca_txtfullname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtfullname.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtfullname.setText("FULLNAME:");
        jPanel1.add(ca_txtfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        ca_txtusername.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtusername.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtusername.setText("USERNAME:");
        jPanel1.add(ca_txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        ca_txtpassword.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtpassword.setText("PASSWORD:");
        jPanel1.add(ca_txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        ca_fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ca_fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ca_fullnameActionPerformed(evt);
            }
        });
        jPanel1.add(ca_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 219, 30));

        ca_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ca_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 218, 30));

        ca_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ca_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 146, 218, 30));

        ca_createbutton.setBackground(new java.awt.Color(255, 255, 255));
        ca_createbutton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_createbutton.setForeground(new java.awt.Color(51, 51, 51));
        ca_createbutton.setText("CREATE");
        ca_createbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ca_createbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ca_createbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(ca_createbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 270, 110, 30));

        ca_backbutton.setBackground(new java.awt.Color(255, 255, 255));
        ca_backbutton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_backbutton.setForeground(new java.awt.Color(51, 51, 51));
        ca_backbutton.setText("BACK");
        ca_backbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ca_backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ca_backbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(ca_backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 115, 30));

        ca_txtemail.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtemail.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtemail.setText("EMAIL:");
        jPanel1.add(ca_txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 73, -1));

        ca_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ca_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 46, 210, 30));

        ca_txtemail1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtemail1.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtemail1.setText("PHONE NO:");
        jPanel1.add(ca_txtemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 90, -1));

        ca_phonenumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ca_phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 210, 30));

        ca_txtemail2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtemail2.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtemail2.setText("AGE:");
        jPanel1.add(ca_txtemail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 73, -1));

        ca_birthdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ca_birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 210, 30));

        ca_txtaddress.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtaddress.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtaddress.setText("ADDRESS:");
        jPanel1.add(ca_txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 186, -1, -1));

        ca_txtemail3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtemail3.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtemail3.setText("BIRTHDATE:");
        jPanel1.add(ca_txtemail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        ca_age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ca_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 210, 30));

        ca_address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ca_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 220, 30));

        CreateAccount.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 320));

        jTabbedPane1.addTab("tab2", CreateAccount);

        ResetConfirm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab3", ResetConfirm);

        ResetPassword.setBackground(new java.awt.Color(204, 204, 255));
        ResetPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel4.setOpaque(false);

        rp_txtname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        rp_txtname.setForeground(new java.awt.Color(255, 255, 255));
        rp_txtname.setText("ENTER YOUR NAME:");

        rp_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rp_findbutton.setBackground(new java.awt.Color(102, 102, 255));
        rp_findbutton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        rp_findbutton.setText("SEARCH");
        rp_findbutton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        rp_findbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_findbuttonActionPerformed(evt);
            }
        });

        rp_backbutton.setBackground(new java.awt.Color(102, 102, 255));
        rp_backbutton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        rp_backbutton.setText("BACK");
        rp_backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rp_backbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rp_txtname)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(rp_findbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rp_backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(rp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(rp_txtname)
                .addGap(18, 18, 18)
                .addComponent(rp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rp_findbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rp_backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        ResetPassword.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jTabbedPane1.addTab("tab4", ResetPassword);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 610, 400));

        sidePanel.setBackground(new java.awt.Color(204, 204, 255));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CraeteAccountButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        CraeteAccountButton.setForeground(new java.awt.Color(51, 51, 51));
        CraeteAccountButton.setText("Create Account");
        sidePanel.add(CraeteAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 84, 160, -1));

        ResetPasswordBUtton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ResetPasswordBUtton.setForeground(new java.awt.Color(51, 51, 51));
        ResetPasswordBUtton.setText("Reset Password");
        sidePanel.add(ResetPasswordBUtton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170, -1));

        AboutButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        AboutButton.setForeground(new java.awt.Color(51, 51, 51));
        AboutButton.setText("About");
        sidePanel.add(AboutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, -1));

        LoginButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(51, 51, 51));
        LoginButton.setText("Login");
        sidePanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 42, 160, -1));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 190, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
           jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void LoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButton1ActionPerformed
    jTabbedPane1.setSelectedIndex(1);
        if (logintxt_username.getText().equals(" ")){
            JOptionPane.showMessageDialog(null, "Please fill out username:");
        } else if (logintxt_password.getText().equals(" ")) {
            JOptionPane.showMessageDialog(null, "Please fill out username:");

        //} else if (login_password.getText().equals("xhinsade123") && login_password.getText().contains("xhinsade123")) {
            JOptionPane.showMessageDialog(null, "You have successfully Login");
            //HomePage1 home = new HomePage1();
            //home.setVisible(true);
            this.dispose();
        } else if (!login_password.getText().equals("xhinsade123") && !login_password.getText().contains("xhinsade123")) {
            JOptionPane.showMessageDialog(null,"You have enter incorrect username or password!!", "Message",JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,"Please fill out the username or password!!", "Message",JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_LoginButton1ActionPerformed

    private void ca_fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ca_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ca_fullnameActionPerformed

    private void ca_createbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ca_createbuttonActionPerformed
        String fullname = ca_fullname.getText();
        String username = ca_username.getText();
        String password = ca_password.getText();
        String address = ca_address.getText();
        String email = ca_email.getText();
        String age = ca_age.getText();
        String number  = ca_phonenumber.getText();
        String birthdate = ca_birthdate.getText();

        if (fullname.isEmpty() || username.isEmpty() || password.isEmpty() || address.isEmpty() || email.isEmpty() || age.isEmpty() || number.isEmpty() || birthdate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill up the form properly", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to create this account?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(null, "You've successfully created an account");
               
               

            } else if (option == JOptionPane.NO_OPTION) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_ca_createbuttonActionPerformed

    private void ca_backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ca_backbuttonActionPerformed
       
    }//GEN-LAST:event_ca_backbuttonActionPerformed

    private void rp_findbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_findbuttonActionPerformed

        String fullname = rp_name.getText();
        if (!rp_name.getText().equals("xhinsade"))  {
            JOptionPane.showMessageDialog(null, "Please fill out username:", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (rp_name.getText().equals("xhinsade")) {
            JOptionPane.showMessageDialog(null, "Given name is found!!");
            //RESET_CONFIRM confirmation = new RESET_CONFIRM();
            //confirmation.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Given name not Found!!", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rp_findbuttonActionPerformed

    private void rp_backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rp_backbuttonActionPerformed
        
    }//GEN-LAST:event_rp_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutButton;
    private javax.swing.JButton CraeteAccountButton;
    private javax.swing.JPanel CreateAccount;
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton ForgotPasswordButton;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton LoginButton1;
    private javax.swing.JPanel ResetConfirm;
    private javax.swing.JPanel ResetPassword;
    private javax.swing.JButton ResetPasswordBUtton;
    private javax.swing.JTextField ca_address;
    private javax.swing.JTextField ca_age;
    private javax.swing.JButton ca_backbutton;
    private javax.swing.JTextField ca_birthdate;
    private javax.swing.JButton ca_createbutton;
    private javax.swing.JTextField ca_email;
    public javax.swing.JTextField ca_fullname;
    private javax.swing.JPasswordField ca_password;
    private javax.swing.JTextField ca_phonenumber;
    private javax.swing.JLabel ca_txtaddress;
    private javax.swing.JLabel ca_txtemail;
    private javax.swing.JLabel ca_txtemail1;
    private javax.swing.JLabel ca_txtemail2;
    private javax.swing.JLabel ca_txtemail3;
    private javax.swing.JLabel ca_txtfullname;
    private javax.swing.JLabel ca_txtpassword;
    private javax.swing.JLabel ca_txtusername;
    private javax.swing.JTextField ca_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField login_password;
    private javax.swing.JTextField login_username;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JLabel logintxt_password;
    private javax.swing.JLabel logintxt_username;
    private javax.swing.JButton rp_backbutton;
    private javax.swing.JButton rp_findbutton;
    private javax.swing.JTextField rp_name;
    private javax.swing.JLabel rp_txtname;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
